services:
  - type: web
    name: linkedin-job-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LINKEDIN_LI_AT
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: linkedin_jobs
      - key: MONGO_COLLECTION
        value: jobs
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: URLS_FILE
        value: config/urls.txt
      - key: MAX_PAGES
        value: "5"
      - key: URLS_FILE_UNDER10
        value: config/urls_under10.txt
      - key: MAX_PAGES_UNDER10
        value: "2"
      - key: GDRIVE_COMPANIES_URL
        sync: false
      - key: GDRIVE_GID_HIGH_PREF
        value: "0"
      - key: GDRIVE_GID_SKIP
        value: "1877286130"
      - key: NO_NOTIFY
        value: "false"
      - key: CHROMEDRIVER_HEADLESS
        value: "true"